export interface Realisation {
    id: number;
    url: string;
    title: string;
    category: 'Entreprises' | 'Particuliers' | 'Bébé' | 'Accessoires';
    desc: string;
}

export const REALISATIONS: Realisation[] = [
    { id: 1, url: "/images/realisations/sac-personnalise-brode-octavia.webp", title: "Sac à Dos Octavia", category: "Bébé", desc: "Petit sac à dos en velours côtelé rose avec rabat fleuri et prénom brodé." },
    { id: 2, url: "/images/realisations/poules-decoratives-brodees.webp", title: "Poules Décoratives", category: "Accessoires", desc: "Série de poules en tissu aux motifs variés pour une décoration artisanale." },
    { id: 3, url: "/images/realisations/petit-sac-motif-brode.webp", title: "Sac à Langer Motifs", category: "Bébé", desc: "Grand sac de voyage ou à langer avec motifs animaux et coeurs." },
    { id: 4, url: "/images/realisations/serviette-personnalisee-lea-velo.webp", title: "Serviette Léa", category: "Particuliers", desc: "Serviette éponge avec broderie détaillée d'un vélo fleuri et prénom." },
    { id: 5, url: "/images/realisations/paniers-brodes-personnalises-pio.webp", title: "Panier de Rangement Pio", category: "Bébé", desc: "Paniers en tissu coordonnés avec lingettes lavables et prénom brodé." },
    { id: 6, url: "/images/realisations/serviette-brodee-happy-cats.webp", title: "Serviette Happy Cats", category: "Particuliers", desc: "Broderie ludique d'une rangée de chats colorés sur serviette beige." },
    { id: 7, url: "/images/realisations/trousse-velours-rose-brodee.webp", title: "Trousse Velours", category: "Accessoires", desc: "Trousse de toilette en velours côtelé rose avec doublure fleurie." },
    { id: 8, url: "/images/realisations/protege-carnet-sante-animaux.webp", title: "Protège Carnet Santé", category: "Bébé", desc: "Housse de protection personnalisée avec motifs renard, élan et raton laveur." },
    { id: 9, url: "/images/realisations/banane-brodee-je-roule-ma-bosse.webp", title: "Sac Banane Message", category: "Accessoires", desc: "Banane XL grise avec texte humoristique brodé en doré." },
    { id: 10, url: "/images/realisations/ourson-brode-serviette-naissance.webp", title: "Serviette Ourson", category: "Bébé", desc: "Broderie douce d'un ours en peluche avec nœud vert sur éponge blanche." },
    { id: 11, url: "/images/realisations/serviette-brodee-chiens-orphee-nala.webp", title: "Portraits Chiens", category: "Particuliers", desc: "Portrait double de chiens (Orphée & Nala) réalisé en broderie haute précision." },
    { id: 12, url: "/images/realisations/serviette-brodee-chien-clyne.webp", title: "Portrait Clyne", category: "Particuliers", desc: "Broderie réaliste d'un Border Collie avec le nom de l'animal." },
    { id: 13, url: "/images/realisations/serviette-brodee-renard-simon.webp", title: "Serviette Simon", category: "Bébé", desc: "Motif renard malicieux brodé avec le prénom pour un enfant." },
    { id: 14, url: "/images/realisations/souris-brodee-cadeau-noel.webp", title: "Souris de Noël", category: "Particuliers", desc: "Petite souris brodée avec son cadeau, idéale pour les fêtes." },
    { id: 15, url: "/images/realisations/cheval-brode-serviette-blanche.webp", title: "Cheval Majestueux", category: "Particuliers", desc: "Broderie complexe d'une tête de cheval avec détails de crinière." },
    { id: 16, url: "/images/realisations/trousse-toilette-transparente-personnalisee.webp", title: "Trousse Transparente", category: "Accessoires", desc: "Pochette de voyage avec fenêtres transparentes et détails à pois bleus." },
    { id: 17, url: "/images/realisations/pochette-brodee-motif-moto.webp", title: "Étui Moto", category: "Accessoires", desc: "Housse de protection bleue avec broderie dynamique de motocross." },
    { id: 18, url: "/images/realisations/pochette-personnalisee-marylou.webp", title: "Pochette Marylou", category: "Accessoires", desc: "Housse coordonnée avec prénom brodé en bleu profond." },
    { id: 19, url: "/images/realisations/trousse-toilette-eponge-brodee.webp", title: "Trousse Nid d'Abeille", category: "Accessoires", desc: "Grande trousse en tissu gaufre marron avec étiquette simili-cuir." },
    { id: 20, url: "/images/realisations/serviette-brodee-leo-ocean.webp", title: "Serviette Léo Mer", category: "Bébé", desc: "Thème marin avec baleine, tortue et crabe pour le petit Léo." },
    { id: 21, url: "/images/realisations/sac-dos-lion-flove.webp", title: "Sac à Dos Lion", category: "Bébé", desc: "Sac enfant vert sapin avec broderie Simba et prénom Flove." },
    { id: 22, url: "/images/realisations/bavoir-bebe-mon-premier-noel.webp", title: "Bavoir Premier Noël", category: "Bébé", desc: "Bavoir éponge beige et tissu rennes, brodage festif." },
    { id: 23, url: "/images/realisations/bavoir-mickey-j-peux-pas-j-ai-biberon.webp", title: "Bavoir Mickey", category: "Bébé", desc: "Humour et finesse avec ce bavoir Mickey Mouse rouge et blanc." },
    { id: 24, url: "/images/realisations/bavoir-souris-mini-mais-costaud.webp", title: "Bavoir Mini Costaud", category: "Bébé", desc: "Bavoir vert olive avec souris florale et texte brodé." },
    { id: 25, url: "/images/realisations/bavoir-noel-vert-rennes.webp", title: "Bavoir Noël Vert", category: "Bébé", desc: "Modèle spécial fêtes avec tissu imprimé forêt et rennes." },
    { id: 26, url: "/images/realisations/bavoir-peppa-pig-mini-mais-costaud.webp", title: "Bavoir Peppa Pig", category: "Bébé", desc: "Personnage favori avec texte personnalisé sur éponge rose." },
    { id: 27, url: "/images/realisations/bavoir-lion-j-peux-pas-j-ai-biberon.webp", title: "Bavoir Lion Mint", category: "Bébé", desc: "Tissu bulles menthe à l'eau et broderie lionne." },
    { id: 28, url: "/images/realisations/bavoir-stitch-rose-c-est-mon-ami.webp", title: "Bavoir Stitch", category: "Bébé", desc: "Douceur rose avec le personnage de Stitch brodé." },
    { id: 29, url: "/images/realisations/bavoir-poissons-j-peux-pas-j-ai-biberon.webp", title: "Bavoir Poissons", category: "Bébé", desc: "Éponge marine et tissu à motifs poissons bleus." },
    { id: 30, url: "/images/realisations/bavoir-noel-jaune-rennes.webp", title: "Bavoir Noël Jaune", category: "Bébé", desc: "Variante lumineuse en jaune moutarde pour les fêtes." },
    { id: 31, url: "/images/realisations/sac-main-lin-broderie-discrete.webp", title: "Sac à Main Lin", category: "Accessoires", desc: "Petit sac élégant en lin beige avec bandoulière à motifs ethniques." },
    { id: 32, url: "/images/realisations/banane-velours-violet-chic.webp", title: "Banane Velours Violet", category: "Accessoires", desc: "Accessoire tendance avec bandoulière large travaillée." },
    { id: 33, url: "/images/realisations/doudou-bavoir-mae-graffiti.webp", title: "Doudou Mae", category: "Bébé", desc: "Style urbain graffiti brodé sur doudou plat vert." },
    { id: 34, url: "/images/realisations/chien-broderie-serviette-detail.webp", title: "Détail Chien", category: "Particuliers", desc: "Gros plan sur une broderie haute fidélité de portrait canin." },
    { id: 35, url: "/images/realisations/serviette-brodee-chien-marie.webp", title: "Serviette Marie", category: "Particuliers", desc: "Chien blanc (Samoyède) brodé sur éponge marron foncé." },
    { id: 36, url: "/images/realisations/serviette-brodee-audi-axel.webp", title: "Serviette Audi Axel", category: "Particuliers", desc: "Set de toilette bleu canard avec voiture Audi brodée." },
    { id: 37, url: "/images/realisations/pandas-brodes-bambou.webp", title: "Duo Pandans", category: "Bébé", desc: "Broderie de deux pandas jouant avec du bambou sur serviette." },
    { id: 38, url: "/images/realisations/monstre-rigolo-brode.webp", title: "Monstre Rigolo", category: "Bébé", desc: "Gros yeux et sourire pour cette broderie originale sur éponge verte." },
    { id: 39, url: "/images/realisations/serviette-brodee-tendre-moment.webp", title: "Serviette Tendre Moment", category: "Particuliers", desc: "Calligraphie élégante brodée sur éponge grise à pointillés." },
    { id: 40, url: "/images/realisations/chat-orange-brode-serviette.webp", title: "Petit Chat Orange", category: "Particuliers", desc: "Silhouette de chaton réalisée en remplissage de fil orange." },
    { id: 41, url: "/images/realisations/fleur-noire-stylisee-broderie.webp", title: "Fleur Stylisée", category: "Particuliers", desc: "Design minimaliste d'une fleur noire sur support blanc." },
    { id: 42, url: "/images/realisations/serviette-happy-cats-multicouleurs.webp", title: "Happy Cats Multi", category: "Particuliers", desc: "Version colorée de la broderie chats sur serviette éponge." },
    { id: 43, url: "/images/realisations/canard-lunettes-whatever-brode.webp", title: "Canard Whatever", category: "Particuliers", desc: "Côté décalé avec ce canard à lunettes de soleil." },
    { id: 44, url: "/images/realisations/pere-noel-brode-traditionnel.webp", title: "Père Noël", category: "Particuliers", desc: "Grande broderie de Noël colorée avec sac de cadeaux." },
    { id: 45, url: "/images/realisations/bavoir-bebe-noel-rouge.webp", title: "Bavoir Noël Rouge", category: "Bébé", desc: "Éponge rouge intense avec message de Noël brodé." },
    { id: 46, url: "/images/realisations/licorne-brodee-trousse-serviette.webp", title: "Ensemble Licorne", category: "Bébé", desc: "Duo trousse et serviette rose avec licorne arc-en-ciel." },
    { id: 47, url: "/images/realisations/grenouille-rigolote-brodee.webp", title: "Grenouille", category: "Bébé", desc: "Sourire vert brodé sur serviette de toilette pour enfant." },
    { id: 48, url: "/images/realisations/serviette-brodee-cheval-pauline.webp", title: "Serviette Pauline", category: "Particuliers", desc: "Cheval au galop brodé avec précision." },
    { id: 49, url: "/images/realisations/fleur-stylisee-christelle.webp", title: "Serviette Christelle", category: "Particuliers", desc: "Motif floral brun et prénom sur éponge écrue." },
    { id: 50, url: "/images/realisations/serviette-lionne-fleurs-sonia.webp", title: "Serviette Sonia", category: "Bébé", desc: "Lionne entourée de fleurs et papillons sur éponge rose." },
    { id: 51, url: "/images/realisations/serviette-brodee-van-surf.webp", title: "Van Surf", category: "Particuliers", desc: "Thème évasion avec van vintage, planches et fleurs d'hibiscus." },
    { id: 52, url: "/images/realisations/banane-moumoute-blanche-moderne.webp", title: "Banane Moumoute", category: "Accessoires", desc: "Sac banane en tissu polaire blanc, ultra doux et moderne." }
];
